site_name: Shiyang's Blog
site_url: https://shiyang07ca.github.io/
site_description: Cheese is power
repo_url: https://github.com/shiyang07ca/shiyang07ca.github.io

docs_dir: docs
site_dir: site

theme:
  name: readthedocs
  language: zh
  highlightjs: true
  hljs_languages:
    - python
    - bash
    - yaml

nav:
  - 主页: index.md
  - 芦苇日记:
      - 2026: content/diary/2026.md
  - 厨房备忘录:
      - 猪肉类: content/cookbook/猪肉类.md
      - 蔬菜类: content/cookbook/蔬菜类.md
      - 水产类: content/cookbook/水产类.md
      - 小吃类: content/cookbook/小吃类.md
      - 凉菜类: content/cookbook/凉菜类.md
      - 汤类: content/cookbook/汤类.md
      - 牛羊肉类: content/cookbook/牛羊肉类.md
      - 烧烤: content/cookbook/烧烤.md
      - 主食类: content/cookbook/主食类.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - en
        - ja
  - rss:
      match_path: "content/.*"
      date_from_meta:
        as_creation: date
        as_update: updated

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shiyang07ca
